name: Unix Script

on:
  workflow_dispatch:
    inputs:
      name:
jobs:
  run_unix:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with: 
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Print the hostname
      run: hostname
    - name: JAVA version
      run: java --version
    - name: user 
      run: whoami
    - name: Print the input variable
      run: echo "Variable is $name"
  run_unix:
    steps: 
    - name: Print Name
      run: echo "My name is Ranganath R"
